/// <reference types="nativewind/types" />

// NOTE: This file should not be edited and should be committed with your source code. It is generated by NativeWind.

export interface User {
  user_id: number;
  username: string;
  first_name: string;
  last_name: string;
  password: string; // hashed
  email: string;
  date_of_birth: Date | null;
  created_at: Date;
  follower_count: number;
  following_count: number;
}

export interface Post {
  post_id: number;
  user_id: number;
  content: string;
  likes: number;
  is_anonymous: boolean;
  boosted_until: Date | null;
  media_url: string | null;
  media_type: 'image' | 'video' | null;
  created_at: Date;
}

export interface Comment {
  comment_id: number;
  post_id: number;
  user_id: number;
  parent_comment_id: number | null;
  content: string;
  created_at: Date;
}

export interface PostTag {
  post_id: number;
  tag: string;
}

export interface Ad {
  ad_id: number;
  user_id: number;
  content: string;
  media_url: string | null;
  media_type: 'image' | 'video' | null;
  boosted_until: Date | null;
  created_at: Date;
}

export interface UserToken {
  user_id: number;
  token_count: number;
}

export interface UserLike {
  user_id: number;
  post_id: number;
  created_at: Date;
}

export interface TrendingTag {
  tag: string;
  like_count: number;
  comment_count: number;
  last_updated: Date;
}

export interface Follow {
  follower_id: number;
  followed_id: number;
  created_at: Date;
}
